#
# LICENSE UPL 1.0
#
# Copyright (c) 1982-2020 Oracle and/or its affiliates. All rights reserved.
#
# Since: January, 2020
# Author: gerald.venzl@oracle.com
# Description: Creates an Oracle Linux virtual machine.
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'fileutils'

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# INSTALL PLUGIN RELLOAD
unless Vagrant.has_plugin?("vagrant-reload")
  puts 'Installing vagrant-reload Plugin...'
  system('vagrant plugin install vagrant-reload')
end

# INSTALL PLUGIN VBguest
unless Vagrant.has_plugin?("vagrant-vbguest")
  puts 'Installing vagrant-vbguest Plugin...'
  system('vagrant plugin install vagrant-vbguest')
end

#Define VM
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # VM ol9_server01 - Master
  config.vm.define "ol9-server01"  do |ol9_server01|
    # Box metadata location and box name
    BOX_URL = "https://oracle.github.io/vagrant-projects/boxes"
    BOX_NAME = "oraclelinux/9"
    ol9_server01.vm.box = BOX_NAME
    ol9_server01.vm.box_url = "#{BOX_URL}/#{BOX_NAME}.json"
    ol9_server01.vm.box_download_insecure=true
    ol9_server01.vbguest.no_install  = true
    ol9_server01.vbguest.auto_update = false
    ol9_server01.vbguest.no_remote   = true


    # VARIABLE HOSTNAME
    VM_MASTER_NAME= "ol9-server01"

    # HOSTNAM
    ol9_server01.vm.hostname =VM_MASTER_NAME

    # NETWORK
    ol9_server01.vm.network "public_network",ip: "192.168.0.130",nic_type: "virtio",mode: "bridge",bridge: [
      "Intel(R) I211 Gigabit Network Connection"
    ]
    ol9_server01.vm.network "private_network",ip: "172.36.12.230",nic_type: "virtio"

    # MOUNTS
    ol9_server01.vm.synced_folder ".", "/vagrant", disabled: true
    ol9_server01.vm.synced_folder "../../../security/", "/home/vagrant/security"
    ol9_server01.vm.synced_folder "../../../configs/linux/", "/home/vagrant/configs"
    ol9_server01.vm.synced_folder "../../../scripts/linux/", "/home/vagrant/scripts"

    # PROVIDER
    ol9_server01.vm.provider "virtualbox" do |vb|
      vb.linked_clone = true
      vb.name =VM_MASTER_NAME
      vb.memory = 2048
      vb.cpus = 2
    end

    # SSH,FIREWALLD,SELINUX, UPDATES AND PROFILE
    ol9_server01.vm.provision "shell", path: "../../../scripts/linux/commons/userdata-ol9.sh"

    # CONFIGURE BIND SERVER MASTER
    ol9_server01.vm.provision "shell", path: "../../../scripts/linux/bind/userdata-bind-master.sh"

  end

  # VM debian_server01 - Slave
  config.vm.define "debian-server01"  do |debian_server01|
    debian_server01.vm.box = "debian/bullseye64"
    debian_server01.vm.box_download_insecure=true
    debian_server01.vbguest.no_install  = true
    debian_server01.vbguest.auto_update = false
    debian_server01.vbguest.no_remote   = true

    # VARIABLE HOSTNAME
    VM_SLAVE_NAME= "debian-server01"

    # HOSTNAME
    debian_server01.vm.hostname =VM_SLAVE_NAME

    # NETWORK
    debian_server01.vm.network "public_network",ip: "192.168.0.140",mode: "bridge",bridge: [
      "Intel(R) I211 Gigabit Network Connection"
    ]
    debian_server01.vm.network "private_network",ip: "172.36.12.240"

    # MOUNTS
    debian_server01.vm.synced_folder ".", "/vagrant", disabled: true
    debian_server01.vm.synced_folder "../../../security/", "/home/vagrant/security"
    debian_server01.vm.synced_folder "../../../configs/linux/", "/home/vagrant/configs"
    debian_server01.vm.synced_folder "../../../scripts/linux/", "/home/vagrant/scripts"

    #PROVIDER
    debian_server01.vm.provider "virtualbox" do |vb|
      vb.linked_clone = true
      vb.name =VM_SLAVE_NAME
      vb.memory = 2048
      vb.cpus = 2
    end

    # SSH,FIREWALLD,SELINUX, UPDATES AND PROFILE    
    debian_server01.vm.provision "shell", path: "../../../scripts/linux/commons/userdata-debian.sh"

    # CONFIGURE BIND SLAVE
    debian_server01.vm.provision "shell", path: "../../../scripts/linux/bind/userdata-bind-slave.sh"
  end

  # VM debian_server02 - Forward
  config.vm.define "debian-server02"  do |debian_server02|
    debian_server02.vm.box = "debian/bullseye64"
    debian_server02.vm.box_download_insecure=true
    debian_server02.vbguest.no_install  = true
    debian_server02.vbguest.auto_update = false
    debian_server02.vbguest.no_remote   = true

    # VARIABLE HOSTNAME
    VM_FORWARDING_NAME= "debian-server02"

    # HOSTNAME
    debian_server02.vm.hostname =VM_FORWARDING_NAME

    # NETWORK
    debian_server02.vm.network "public_network",ip: "192.168.0.141",mode: "bridge",bridge: [
      "Intel(R) I211 Gigabit Network Connection"
    ]
    debian_server02.vm.network "private_network",ip: "172.36.12.241"

    # MOUNTS
    debian_server02.vm.synced_folder ".", "/vagrant", disabled: true
    debian_server02.vm.synced_folder "../../../security/", "/home/vagrant/security"
    debian_server02.vm.synced_folder "../../../configs/linux/", "/home/vagrant/configs"
    debian_server02.vm.synced_folder "../../../scripts/linux/", "/home/vagrant/scripts"  

    #PROVIDER
    debian_server02.vm.provider "virtualbox" do |vb|
      vb.linked_clone = true
      vb.name =VM_FORWARDING_NAME
      vb.memory = 2048
      vb.cpus = 2
    end

    # SSH,FIREWALLD,SELINUX, UPDATES AND PROFILE
    debian_server02.vm.provision "shell", path: "../../../scripts/linux/commons/userdata-debian.sh"

    # CONFIGURE BIND FORWARD
    debian_server02.vm.provision "shell", path: "../../../scripts/linux/bind/userdata-bind-forwarding.sh"

  end

  # VM ol9_server02 - Caching
  config.vm.define "ol9-server02"  do |ol9_server02|
    BOX_URL = "https://oracle.github.io/vagrant-projects/boxes"
    BOX_NAME = "oraclelinux/9"
    ol9_server02.vm.box = BOX_NAME
    ol9_server02.vm.box_url = "#{BOX_URL}/#{BOX_NAME}.json"
    ol9_server02.vm.box_download_insecure=true
    ol9_server02.vbguest.no_install  = true
    ol9_server02.vbguest.auto_update = false
    ol9_server02.vbguest.no_remote   = true

    # VARIABLE HOSTNAME
    VM_CACHING_NAME= "ol9-server02"

    # HOSTNAME
    ol9_server02.vm.hostname =VM_CACHING_NAME

    # NETWORK
    ol9_server02.vm.network "public_network",ip: "192.168.0.131",nic_type: "virtio",mode: "bridge",bridge: [
      "Intel(R) I211 Gigabit Network Connection"
    ]
    ol9_server02.vm.network "private_network",ip: "172.36.12.231",nic_type: "virtio"

    # MOUNTS
    ol9_server02.vm.synced_folder ".", "/vagrant", disabled: true
    ol9_server02.vm.synced_folder "../../../security/", "/home/vagrant/security"
    ol9_server02.vm.synced_folder "../../../configs/linux/", "/home/vagrant/configs"
    ol9_server02.vm.synced_folder "../../../scripts/linux/", "/home/vagrant/scripts"

    # PROVIDER
    ol9_server02.vm.provider "virtualbox" do |vb|
      vb.linked_clone = true
      vb.name =VM_CACHING_NAME
      vb.memory = 2048
      vb.cpus = 2
    end

    # SSH,FIREWALLD,SELINUX, UPDATES AND PROFILE
    ol9_server02.vm.provision "shell", path: "../../../scripts/linux/commons/userdata-ol9.sh"

    # CONFIGURE BIND CACHING
    ol9_server02.vm.provision "shell", path: "../../../scripts/linux/bind/userdata-bind-caching.sh"
  end

  # VM ol9_client01 - Client
  config.vm.define "ol9-client01"  do |ol9_client01|
    BOX_URL = "https://oracle.github.io/vagrant-projects/boxes"
    BOX_NAME = "oraclelinux/9"
    ol9_client01.vm.box = BOX_NAME
    ol9_client01.vm.box_url = "#{BOX_URL}/#{BOX_NAME}.json"
    ol9_client01.vm.box_download_insecure=true
    ol9_client01.vbguest.no_install  = true
    ol9_client01.vbguest.auto_update = false
    ol9_client01.vbguest.no_remote   = true

    # VARIABLE HOSTNAME
    VM_CLIENT_NAME= "ol9-client01"

    # HOSTNAME
    ol9_client01.vm.hostname =VM_CLIENT_NAME

    # NETWORK
    ol9_client01.vm.network "public_network",ip: "192.168.0.150",nic_type: "virtio",mode: "bridge",bridge: [
      "Intel(R) I211 Gigabit Network Connection"
    ]
    ol9_client01.vm.network "private_network",ip: "172.36.12.250",nic_type: "virtio"

    # MOUNTS
    ol9_client01.vm.synced_folder ".", "/vagrant", disabled: true
    ol9_client01.vm.synced_folder "../../../security/", "/home/vagrant/security"
    ol9_client01.vm.synced_folder "../../../configs/linux/", "/home/vagrant/configs"    
    ol9_client01.vm.synced_folder "../../../scripts/linux/", "/home/vagrant/scripts"
    ol9_client01.vm.synced_folder "../../../test/linux/", "/home/vagrant/test"

    # PROVIDER
    ol9_client01.vm.provider "virtualbox" do |vb|
      vb.linked_clone = true
      vb.name =VM_CLIENT_NAME
      vb.memory = 2048
      vb.cpus = 1
    end

    # SSH,FIREWALLD,SELINUX, UPDATES AND PROFILE
    ol9_client01.vm.provision "shell", path: "../../../scripts/linux/commons/userdata-ol9.sh"

    # CONFIGURE SERVER BIND CLIENT
    ol9_client01.vm.provision "shell", path: "../../../scripts/linux/bind/userdata-bind-client.sh"

    # EXECUTE TEST STACK BIND
    ol9_client01.vm.provision "shell", path: "../../../scripts/linux/bind/check-bind-stack.sh"

  end
end